version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jobparser-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

volumes:
  db_data:
